### ISSUE TITLE
Tracking Progress

### ISSUE THREAD

**Issue by halotroop2288** [c08oprkiua/godot-wii-u#3]
# Progress

## Vital Core Features

These are absolutely required for starting the engine. Without them, it may not even compile.

- [ ] Threading (coreinit)
  - [ ] Thread (coreinit/thread)
  - [ ] Mutex (coreinit/mutex)
  - [ ] Semaphore (coreinit/semaphore)
- [ ] Crash handling
- [ ] OS integration
  - [x] Software information
  - [x] Hardware information

## Input / Output

These can wait until the core features are implemented, but are vital to the everyday usage of the engine.

- [ ] Filesystem access
- [ ] Graphics (gx2, gx2r)
- [ ] Audio (sndcore2)
- [x] Input
  - [x] Gamepad (VPAD)
  - [x] Wii remotes (KPAD)
  - [x] GameCube Controllers (HPAD)
  - [ ] HID Devices

## OS / Platform features

These can be important for some game features, but are not absolutely vital.

- [ ] Home Menu (ProcUI)
- [ ] Keyboard overlay (swkbd)
- [ ] Time

## Optional Tertiary Features

These can be added last, as they are only required for specific niches, such as multiplayer.

- [ ] Networking
  - [ ] HTTPClient

**Comment by MetalMaxMX** [comment]
Any updates on this? Is it a good idea to now keep up with Godot 4.3 since that has been released?

**Comment by c08oprkiua** [comment]
I have some progress that I haven't pushed because I haven't had git set up for my godot working codebase, but it's several months old and doesn't compile; I have not been working on it recently. 

As for keeping up with Godot 4.x, the thing is, the way graphics work internally keep actively changing, so keeping up with the latest version is going to be a cat and mouse game, and on top of that, I don't even have graphics API experience, so I'd be trying that with no backing experience to even know what I'm doing in the first place. 

That is to say, until Godot 4.x development slows down, don't expect this port to be actively keeping up with it unless someone other than me is the one keeping up that slack.
